export const UPDATE_PAYMENT = 'UPDATE_PAYMENT'
export const UPDATE_PAYMENT_ERROR = 'UPDATE_PAYMENT_ERROR'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_POSTAL = 'UPDATE_POSTAL'
export const UPDATE_ORDER = 'UPDATE_ORDER'
export const UPDATE_LOADING = 'UPDATE_LOADING'
export const UPDATE_REFERRAL_DATE = 'UPDATE_REFERRAL_DATE'
export const UPDATE_SHOW_SCHOOL_CODE = 'UPDATE_SHOW_SCHOOL_CODE'
export const UPDATE_SHOW_PROMO_CODE = 'UPDATE_SHOW_PROMO_CODE'
export const UPDATE_NEW_CARD = 'UPDATE_NEW_CARD'
export const UPDATE_TAX_RATE = 'UPDATE_TAX_RATE'
export const UPDATE_TOTAL = 'UPDATE_TOTAL'
export const UPDATE_PROMO_SUCCESS = 'UPDATE_PROMO_SUCCESS'
export const UPDATE_PROMO_FAILURE = 'UPDATE_PROMO_FAILURE'
export const UPDATE_SHOOL_CODE_SUCCESS = 'UPDATE_SHOOL_CODE_SUCCESS'
export const UPDATE_SHOOL_CODE_FAILURE = 'UPDATE_SHOOL_CODE_FAILURE'
export const UPDATE_SHOW_PROMOCODE_DISCOUNT = 'UPDATE_SHOW_PROMOCODE_DISCOUNT'
export const UPDATE_PROMOCODE_DISCOUNT = 'UPDATE_PROMOCODE_DISCOUNT'
export const UPDATE_PROMOCODE = 'UPDATE_PROMOCODE'
export const UPDATE_SHOOL_CODE = 'UPDATE_SHOOL_CODE'
export const RESET_PAYMENT = 'RESET_PAYMENT'
export const UPDATE_EXPIRATION_BANNER = 'UPDATE_EXPIRATION_BANNER'
export const UPDATE_SHOW_MEMBERSHIP_EXPIRING_MODAL = 'UPDATE_SHOW_MEMBERSHIP_EXPIRING_MODAL'
export const UPDATE_PAYMENT_LOADING = 'UPDATE_PAYMENT_LOADING'



// WEBPACK FOOTER //
// ./src/store/modules/payment/types.js