module.exports = function (Component) {
  Component.options.__i18n = Component.options.__i18n || []
  Component.options.__i18n.push('{"en":{"all_set":"You\u0027re All Set!","one_time_offer":"ONE TIME ONLY OFFER!","benefits_available":"Your SPC membership benefits are now available!","note":"Note","renew":"Membership valid until ","renew_school_portal":"Your membership does not renew automatically and it will expire on:","turn_on_subscription":"Pre-pay ${discountAmount} now & your membership will be valid for 24 months, instead of 12!","click_below_subscribe":"Click below to turn on a subscription and pay for your next full year of SPC at this discounted rate now!","subscribe_now":"TURN ON","click_here_start_saving":"Don\u0027t want to do this now, you will need to pay $11.99 next year.","no_thanks":"No thanks, take me to ","spc_discount":"SPC DISCOUNTS","start_saving":"start saving","download_app":"To get the most out of your SPC experience, please download the SPC app! Happy saving","auto_renew_subscription":"Your membership will automatically renew on: ","visit_profile":"View or edit subscription","toggle_download_app":"Download the SPC app to redeem in-store offers and never miss a deal!","want-discount":"Get {offer} Off"},"fr":{"all_set":"Vous le faites!","one_time_offer":"OFFRE UNIQUE!","benefits_available":"Vos avantages d’adhésion sont disponibles maintenant!","note":"Note","renew":"Adhésion valide jusqu’au ","renew_school_portal":"Votre adhésion n\u0027est pas renouvelée automatiquement et expirera le:","turn_on_subscription":"Prépayez-${discountAmount} maintenant et votre abonnement sera valide pour 24 mois, au lieu de 12!","click_below_subscribe":"Cliquez ci-dessous pour activer votre abonnement et payer votre prochaine année complète avec SPC à tarif réduit dès maintenant !","subscribe_now":"ACTIVER","click_here_start_saving":"Si vous ne souhaitez pas le faire maintenant, vous devrez payer 11,99 $ l\u0027année prochaine.","no_thanks":"Non merci, emmenez-moi aux ","spc_discount":"RABAIS SPC","start_saving":"commencer à économiser","download_app":"Afin de profitez au maximum de votre expérience SPC, veuillez télécharger l\u0027application SPC! Bonne économies","auto_renew_subscription":"Votre adhésion sera renouvelée automatiquement le: ","visit_profile":"Afficher ou modifier l\u0027abonnement","toggle_download_app":"Téléchargez l\u0027application SPC pour échanger les offres en magasin et ne jamais manquer une aubaine!","want-discount":"Obtenez {offer} de rabais"}}')
}



//////////////////
// WEBPACK FOOTER
// ./node_modules/@kazupon/vue-i18n-loader/lib!./node_modules/vue-loader/lib/selector.js?type=customBlocks&index=0!./src/components/Modals/ActivationCompletedModal.vue
// module id = aetO
// module chunks = 0