var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('Modal',{attrs:{"show":_vm.show,"inverted":false},on:{"close":function($event){return _vm.$emit('close')}}},[_c('div',{staticClass:"cibc-container"},[_c('div',{staticClass:"column-one"},[_c('router-link',{staticClass:"spc-button-v2 secondary border-white small",attrs:{"to":"/spc-plus","tag":"button"},nativeOn:{"click":function($event){return _vm.$emit('close')}}},[_c('img',{staticClass:"image",attrs:{"src":require('@/assets/images/cibc/spc-logo-black.png')}})]),_vm._v(" "),_c('h1',{staticClass:"header-text"},[_vm._v(_vm._s(_vm.$t('title')))]),_vm._v(" "),_c('p',{staticClass:"description"},[_vm._v(_vm._s(_vm.$t('description')))]),_vm._v(" "),_c('router-link',{staticClass:"spc-button-v2 secondary border-white medium bottom desktop-img",attrs:{"to":"/spc-plus","tag":"button"},nativeOn:{"click":function($event){return _vm.handleLearnMore($event)}}},[_vm._v(_vm._s(_vm.$t('start_shopping')))])],1),_vm._v(" "),_c('div',{staticClass:"column-two"},[_c('div',{staticClass:"image-container"},[_c('img',{directives:[{name:"lazy",rawName:"v-lazy",value:(require('@/assets/images/cibc/cibc-group.png')),expression:"require('@/assets/images/cibc/cibc-group.png')"}],staticClass:"desktop-img"}),_vm._v(" "),_c('img',{directives:[{name:"lazy",rawName:"v-lazy",value:(require('@/assets/images/cibc/cibc-group-mobile.png')),expression:"require('@/assets/images/cibc/cibc-group-mobile.png')"}],staticClass:"mobile-img"}),_vm._v(" "),_c('router-link',{staticClass:"spc-button-v2 secondary border-white medium bottom mobile-img",attrs:{"to":"/spc-plus","tag":"button"},nativeOn:{"click":function($event){return _vm.$emit('close')}}},[_vm._v(_vm._s(_vm.$t('start_shopping')))])],1),_vm._v(" "),_c('div',{staticClass:"image-two-container"},[_c('img',{attrs:{"src":require('@/assets/images/cibc/spc-cibc-icon.png')}})])])])])}
var staticRenderFns = []
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-58c7f3e0","hasScoped":true,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/Modals/CIBCModal.vue
// module id = null
// module chunks = 