var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('Modal',{attrs:{"show":_vm.show,"inverted":false,"closeButton":_vm.loggedIn || _vm.showCloseBtn},on:{"close":function($event){return _vm.closeLoginModal()}}},[_c('div',{staticClass:"login-container"},[_c('div',[_c('h1',[_vm._v(_vm._s(_vm.$t('title')))])]),_vm._v(" "),_c('div',{staticClass:"join-or-login-btn"},[(!_vm.loggedIn)?_c('router-link',{staticClass:"spc-button-v2 purple",attrs:{"to":"/signup","tag":"button"},nativeOn:{"click":function($event){return _vm.$emit('close')}}},[_vm._v(_vm._s(_vm.$t('create_account')))]):_vm._e(),_vm._v(" "),(!_vm.loggedIn)?_c('router-link',{staticClass:"spc-button-v2 secondary",attrs:{"to":"/login","tag":"button","title":_vm.$t('login_description')},nativeOn:{"click":function($event){return _vm.$emit('close')}}},[_vm._v(_vm._s(_vm.$t('login')))]):_vm._e(),_vm._v(" "),(_vm.loggedIn && _vm.showFreeTrial && !_vm.validMemberWithCard)?_c('button',{staticClass:"spc-button-v2",attrs:{"title":_vm.$t('login_description'),"disabled":_vm.activating},on:{"click":function($event){return _vm.startFreeTrial()}}},[_vm._v(_vm._s(_vm.$t('free_trial')))]):_vm._e(),_vm._v(" "),(_vm.activating)?_c('LineLoader',{attrs:{"inverted":true}}):_vm._e(),_vm._v(" "),(_vm.loggedIn && !_vm.validMemberWithCard && !_vm.showFreeTrial)?_c('router-link',{staticClass:"spc-button-v2 purple",attrs:{"to":"/purchase","tag":"button"},nativeOn:{"click":function($event){return _vm.$emit('close')}}},[_vm._v(_vm._s(_vm.$t('purchase')))]):_vm._e(),_vm._v(" "),(_vm.loggedIn && !_vm.validMemberWithCard)?_c('p',[_vm._v(_vm._s(_vm.$t('already_member')))]):_vm._e(),_vm._v(" "),(_vm.loggedIn && !_vm.validMemberWithCard)?_c('router-link',{staticClass:"register-link",attrs:{"to":"/register","tag":"a","title":_vm.$t('register_description'),"disabled":_vm.activating},nativeOn:{"click":function($event){return _vm.$emit('close')}}},[_vm._v(_vm._s(_vm.$t('registerLink')))]):_vm._e()],1)])])}
var staticRenderFns = []
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-1c2ff67a","hasScoped":true,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/Modals/LoginModal.vue
// module id = null
// module chunks = 