module.exports = function (Component) {
  Component.options.__i18n = Component.options.__i18n || []
  Component.options.__i18n.push('{"en":{"banner":{"title":"Help us, help students.","description":"Everything we do is for the kids. From the savings to the content, our ultimate goal is making student life better. Your help is needed to reach that goal!","action":"View Opportunities"},"who-we-are":{"title":"Our Story","description":"In 1992, our founder, Dean Mazzariol, a new graduate from Ryerson University knew there had to be a way to make student life better – even if it was as simple as saving a few bucks. Thus, SPC was developed to fulfill that “need”. Fast-forward to {year}, SPC has been able to provide over 450 unique deals & gain the title of the #1 Coalition Loyalty Program by Bond Brand Loyalty Survey & Report. The story is still unfolding, and this could be your chance to help write the next chapter."},"the-team":{"title":"The Squad","description":"Get to know the team – or at least the spark notes version!"},"benefits-and-perks":{"title":"Benefits & Perks"},"values-and-principles":{"title":"Values & Principles","values":"Values","principles":"Principles"},"current-openings":{"title":"Join Our Squad","other":"Don’t see a position you’re looking for? Send over your resume to {0} and we’ll keep it on file!","none":"No openings available currently. Please check back later."}},"fr":{"banner":{"title":"Help us, help students.","description":"Everything we do is for the kids. From the savings to the content, our ultimate goal is making student life better. Your help is needed to reach that goal!","action":"View Opportunities"},"who-we-are":{"title":"Our Story","description":"In 1992, our founder, Dean Mazzariol, a new graduate from Ryerson University knew there had to be a way to make student life better – even if it was as simple as saving a few bucks. Thus, SPC was developed to fulfill that “need”. Fast-forward to {year}, SPC has been able to provide over 450 unique deals & gain the title of the #1 Coalition Loyalty Program by Bond Brand Loyalty Survey & Report. The story is still unfolding, and this could be your chance to help write the next chapter."},"the-team":{"title":"The Squad","description":"Get to know the team – or at least the spark notes version!"},"benefits-and-perks":{"title":"Benefits & Perks"},"values-and-principles":{"title":"Values & Principles","values":"Values","principles":"Principles"},"current-openings":{"title":"Join Our Squad","other":"Don’t see a position you’re looking for? Send over your resume to {0} and we’ll keep it on file!","none":"No openings available currently. Please check back later."}}}')
}



//////////////////
// WEBPACK FOOTER
// ./node_modules/@kazupon/vue-i18n-loader/lib!./node_modules/vue-loader/lib/selector.js?type=customBlocks&index=0!./src/components/Links/Careers.vue
// module id = 999K
// module chunks = 57