import * as types from './types'

export default {
  /*
   * notification: {
   *   id,        // autogenerated, will be overridden
   *   content,   // html string to show, required
   *   expiry,    // time in milliseconds for the notification to automatically disappear, optional
   *   callback   // function to call when notification is removed, either manually or automatically, optional
   * }
   */
  pushNotification ({ commit }, notification) {
    commit(types.PUSH_NOTIFICATION, notification)
    if (notification.expiry) {
      setTimeout(() => {
        commit(types.POP_NOTIFICATION, notification)
      }, notification.expiry)
    }
  },
  popNotification ({ commit }, notification) {
    commit(types.POP_NOTIFICATION, notification)
  }
}



// WEBPACK FOOTER //
// ./src/store/modules/notifications/actions.js