var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',[(_vm.title)?_c('div',{staticClass:"title-container"},[_c('h1',[_vm._v(_vm._s(_vm.title))])]):_vm._e(),_vm._v(" "),_c('div',{staticClass:"slider-container"},[(_vm.showArrows)?_c('div',{staticClass:"nav arrow-nav",class:{ hidden: !_vm.showLeftArrow },on:{"click":function($event){return _vm.scrollLeft()}}},[_c('img',{attrs:{"src":require('@/assets/images/icons/general/SPC_UI_ArrowLeft_Grey.svg')}})]):_vm._e(),_vm._v(" "),_c('div',{staticClass:"overflow-container fade-container"},[_c('ul',{ref:"scroll-container",staticClass:"list-reset-horizontal padded-list hide-scrollbar"},_vm._l((_vm.rowData),function(row){return _c('li',{key:row.id},[(_vm.isBts)?_c('BannerTile',{attrs:{"title":row.title,"description":row.description,"previewTitle":row.preview_title,"previewDescription":row.preview_description,"expiry":row.expiry,"isSPCPlus":row.isSPCPlus,"isBts":_vm.isBts,"imagePath":row.imagePath,"isStarted":row.isStarted,"previewImagePath":row.preview_imagePath,"alt":(row.data[row.type] && row.data[row.type][("alt_" + _vm.language)])? row.data[row.type][("alt_" + _vm.language)] : row.data[row.type][("title_" + _vm.language)],"preview":(row.data[row.type] && row.data[row.type][("preview_alt_" + _vm.language)])? row.data[row.type][("preview_alt_" + _vm.language)] : row.data[row.type][("preview_title_" + _vm.language)],"offerPartner":row.data['partner']},on:{"select":function($event){return _vm.handleSelect(row.id, row.isStarted)}}}):_c('BannerTile',{attrs:{"title":row.title,"description":row.description,"expiry":row.expiry,"isSPCPlus":row.isSPCPlus,"imagePath":row.imagePath,"alt":(row.data[row.type] && row.data[row.type]['alt_'+_vm.language])? row.data[row.type]['alt_'+_vm.language] : row.data[row.type]['title_'+_vm.language],"offerPartner":row.data['partner']},on:{"select":function($event){return _vm.handleSelect(row.id)}}})],1)}),0)]),_vm._v(" "),(_vm.showArrows)?_c('div',{staticClass:"nav arrow-nav",class:{ hidden: !_vm.showRightArrow },on:{"click":function($event){return _vm.scrollRight()}}},[_c('img',{attrs:{"src":require('@/assets/images/icons/general/SPC_UI_ArrowRight_Grey.svg')}})]):_vm._e()])])}
var staticRenderFns = []
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-304698fe","hasScoped":true,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/BannerRow.vue
// module id = null
// module chunks = 