module.exports = function (Component) {
  Component.options.__i18n = Component.options.__i18n || []
  Component.options.__i18n.push('{"en":{"about":"About","terms_conditions":"Terms and Conditions","redeem_online":"Redeem online","copy_code_again":"Copy code again","no_code_required":"No code required - continue shopping","join_spc":"JOIN SPC to redeem this offer!","join_spc_plus":"JOIN SPC+ TO REDEEM THIS OFFER!","code_copied":"Promo code copied to clipboard. \\nStart shopping & paste at checkout!","errors":{"offer_expired":"Offer expired","offer_not_found":"Offer not found","code_load_error":"Failed to load code","code_copy_error":"Failed to copy code","url_load_error":"Failed to load URL"},"keep_membership":"Keep your membership with you at all times! Download the SPC app to redeem in-store offers and never miss a discount!","more_from":"More From","most_popular":"Most Popular","you_might_like":"You might also like","download_app_online":"Or download the SPC app to redeem this offer in store!","download_app_instore":"Download the SPC app to redeem this offer in store!","back":"Back","back_to_deals":"Back to Deals","mobile_share_text":"I\u0027m saving money with SPC, and you can too! Check it out."},"fr":{"about":"À-Propos","terms_conditions":"Termes & Conditions","redeem_online":"Échangez en ligne","copy_code_again":"Recopiez le code","no_code_required":"Aucun code requis – suivez le lien suivant","join_spc":"Acheter SPC pour bénéficier de cette offre!","join_spc_plus":"REJOIGNEZ SPC+ POUR UTILISER CETTE OFFRE!","code_copied":"Code promo est copié a votre presse-papier. \\nCommencez á magasiner & collez-le á la caisse","errors":{"offer_expired":"Offre est expirée","offer_not_found":"Offre non trouvée","code_load_error":"Échec du chargement du code","code_copy_error":"Échec de la copie du code","url_load_error":"Échec du chargement de l\u0027URL"},"keep_membership":"Gardez votre adhésion avec vous à tout moment ! Téléchargez l\u0027application SPC pour profiter des offres en magasin et ne manquez jamais une remise !","more_from":"Plus de","most_popular":"Most Popular","you_might_like":"Vous aimerez peut-être aussi","download_app_online":"Ou téléchargez l\u0027application SPC pour profiter de cette offre en magasin !","download_app_instore":"Téléchargez l\u0027application SPC pour profiter de cette offre en magasin !","back":"Arrière","back_to_deals":"Retour aux offres","mobile_share_text":"J\u0027économise de l\u0027argent avec SPC, et vous pouvez aussi! Découvrez-le."}}')
}



//////////////////
// WEBPACK FOOTER
// ./node_modules/@kazupon/vue-i18n-loader/lib!./node_modules/vue-loader/lib/selector.js?type=customBlocks&index=0!./src/components/Deal.vue
// module id = 54WQ
// module chunks = 19