var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{ref:"search-container",staticClass:"search-container",class:{'footer-search': _vm.fromFooter, 'header-adjust': _vm.fromHeader, 'no-vertical-margin': this.$route.name === _vm.pageNames.DEALS},on:{"click":_vm.focusText}},[(_vm.validateDeviceWidth('Desktop', _vm.screenWidth))?_c('img',{staticClass:"search-icon",attrs:{"src":require("@/assets/images/icons/general/search-icon-inactive.svg")},on:{"click":function($event){return _vm.handleSearch()}}}):_vm._e(),_vm._v(" "),(!_vm.validateDeviceWidth('Desktop', _vm.screenWidth))?_c('img',{staticClass:"search-icon",attrs:{"src":require("@/assets/images/icons/general/search-icon.svg")},on:{"click":function($event){return _vm.handleSearch()}}}):_vm._e(),_vm._v(" "),_c('input',{ref:"searchText",staticClass:"search-box",attrs:{"type":"search","placeholder":_vm.showPlaceholder,"disabled":_vm.disabled,"id":"searchField","autocomplete":"off"},domProps:{"value":_vm.value},on:{"input":function($event){_vm.$emit('input', _vm.fixQuotes($event.target.value)), _vm.inputValue = $event.target.value},"keyup":[function($event){if(!$event.type.indexOf('key')&&_vm._k($event.keyCode,"enter",13,$event.key,"Enter")){ return null; }return _vm.handleSearch()},function($event){if(!$event.type.indexOf('key')&&_vm._k($event.keyCode,"esc",27,$event.key,["Esc","Escape"])){ return null; }_vm.$emit('input', ''), _vm.inputValue = ''}],"focus":_vm.onFocus,"blur":_vm.onBlur}}),_vm._v(" "),_c('div',{directives:[{name:"show",rawName:"v-show",value:(_vm.searchFocused),expression:"searchFocused"}],class:[_vm.fromFooter ? 'suggestionsFooter' : 'suggestions' ]},[_c('SpinnerLoading',{directives:[{name:"show",rawName:"v-show",value:(_vm.displayLoader),expression:"displayLoader"}],staticClass:"loading-margin"}),_vm._v(" "),(this.inputValue)?_c('ul',{staticClass:"list-reset"},_vm._l((_vm.uniqueSuggestions),function(suggestion){return _c('li',{key:suggestion,on:{"click":function($event){return _vm.handleSearch(suggestion)}}},[_vm._v("\n          "+_vm._s((typeof suggestion === 'object')? suggestion[_vm.displayKey]: suggestion)+"\n        ")])}),0):_vm._e()],1)])}
var staticRenderFns = []
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-5f74b782","hasScoped":true,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/SearchInput.vue
// module id = null
// module chunks = 