var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('carousel',{attrs:{"autoplay":true,"paginationSize":12,"paginationActiveColor":"#FFFFFF","paginationColor":"#FFFFFF","paginationPosition":"bottom-overlay","speed":1000,"autoplayTimeout":7000,"loop":true,"per-page":1,"navigation-enabled":_vm.isDesktopWeb && _vm.enableNavigation,"adjustableHeight":true}},_vm._l((_vm.bannerAds),function(banner,index){return _c('slide',{key:index},[(_vm.validateDeviceWidth('Desktop', _vm.screenWidth))?_c('img',{staticClass:"image_regular",class:{'no-pointer': !banner.is_clickable},attrs:{"src":_vm.getURL(banner['image_'+_vm.language]),"alt":(banner['alt_'+_vm.language]) ? banner['alt_'+_vm.language] : banner['text_'+_vm.language],"title":(banner['alt_'+_vm.language]) ? banner['alt_'+_vm.language] : banner['text_'+_vm.language]},on:{"click":function($event){return _vm.handleSlideClick(banner['url_'+_vm.language], banner, index)}}}):_vm._e(),_vm._v(" "),(_vm.validateDeviceWidth('Tablet', _vm.screenWidth))?_c('img',{staticClass:"image_tablet",attrs:{"src":_vm.getURL(banner['image_tablet_'+_vm.language]),"alt":(banner['alt_'+_vm.language]) ? banner['alt_'+_vm.language] : banner['text_'+_vm.language],"title":(banner['alt_'+_vm.language]) ? banner['alt_'+_vm.language] : banner['text_'+_vm.language]},on:{"click":function($event){return _vm.handleSlideClick(banner['url_'+_vm.language], banner, index)}}}):_vm._e(),_vm._v(" "),(_vm.validateDeviceWidth('Mobile', _vm.screenWidth))?_c('img',{staticClass:"image_mobile",attrs:{"id":_vm.generateId(index),"src":_vm.getURL(banner['image_mobile_'+_vm.language]),"alt":(banner['alt_'+_vm.language]) ? banner['alt_'+_vm.language] : banner['text_'+_vm.language],"title":(banner['alt_'+_vm.language]) ? banner['alt_'+_vm.language] : banner['text_'+_vm.language]}}):_vm._e()])}),1)}
var staticRenderFns = []
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-c4b80be0","hasScoped":true,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/Common/BannerCarousel.vue
// module id = null
// module chunks = 