var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',[(_vm.title)?_c('div',{staticClass:"title-container"},[_c('h1',[_vm._v(_vm._s(_vm.title))])]):_vm._e(),_vm._v(" "),_c('div',{staticClass:"slider-container"},[(_vm.showArrows)?_c('div',{staticClass:"nav arrow-nav",class:{ hidden: !_vm.showLeftArrow },on:{"click":function($event){return _vm.scrollLeft()}}},[_c('img',{attrs:{"src":require('@/assets/images/icons/general/icon-solid-angle-left.svg')}})]):_vm._e(),_vm._v(" "),_c('div',{staticClass:"overflow-container fade-container"},[_c('ul',{ref:"scroll-container",staticClass:"list-reset-horizontal padded-list hide-scrollbar",on:{"scroll":function($event){return _vm.handleScroll()}}},_vm._l((_vm.collections),function(collection){return _c('li',{key:collection.id},[_c('div',{staticClass:"offer-tile-container",on:{"click":function($event){return _vm.handleCollection(collection)}}},[_c('div',{staticClass:"prop-section"},[_c('div',{staticClass:"overlay"}),_vm._v(" "),_c('img',{directives:[{name:"lazy",rawName:"v-lazy",value:(_vm.getURL(collection['image_large_'+ _vm.language])),expression:"getURL(collection['image_large_'+ language])"}],staticClass:"background-image",attrs:{"alt":""}}),_vm._v(" "),(collection['alt_'+ _vm.language].length <= 125)?_c('div',{staticClass:"description"},[_vm._v(_vm._s(collection['alt_'+ _vm.language]))]):_c('div',{staticClass:"description"},[_vm._v(_vm._s(collection['alt_'+ _vm.language].substr(0,125).concat('...')))]),_vm._v(" "),_c('img',{staticClass:"arrow-img rotate180",attrs:{"src":require("@/assets/images/icons/general/arrow-icon-white.svg"),"alt":"arrow"}})]),_vm._v(" "),_c('div',{staticClass:"banner-info"},[_c('div',{staticClass:"title"},[_vm._v(_vm._s(collection['title_'+ _vm.language]))]),_vm._v(" "),(_vm.validateDeviceWidth('TabletIpad',_vm.screenWidth) || !_vm.validateDeviceWidth('Desktop', _vm.screenWidth))?_c('div',{staticClass:"under-description"},[_vm._v(_vm._s(collection['alt_'+ _vm.language]))]):_vm._e()])])])}),0)]),_vm._v(" "),(_vm.showArrows)?_c('div',{staticClass:"nav arrow-nav",class:{ hidden: !_vm.showRightArrow },on:{"click":function($event){return _vm.scrollRight()}}},[_c('img',{attrs:{"src":require('@/assets/images/icons/general/icon-solid-angle-right.svg')}})]):_vm._e()])])}
var staticRenderFns = []
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-79ff8e30","hasScoped":true,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/Common/CollectionSection.vue
// module id = null
// module chunks = 