export const UPDATE_EMAIL = 'UPDATE_EMAIL'
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'
export const UPDATE_BIRTHDATE = 'UPDATE_BIRTHDATE'
export const UPDATE_SIGNUP_METHOD = 'UPDATE_SIGNUP_METHOD'
export const UPDATE_STEP_ONE_COMPLETE = 'UPDATE_STEP_ONE_COMPLETE'
export const UPDATE_FIRST_NAME = 'UPDATE_FIRST_NAME'
export const UPDATE_LAST_NAME = 'UPDATE_LAST_NAME'
export const UPDATE_EMAIL_OPT_IN = 'UPDATE_EMAIL_OPT_IN'
export const UPDATE_AGREE = 'UPDATE_AGREE'
export const UPDATE_LOGIN_STATUS = 'UPDATE_LOGIN_STATUS'



// WEBPACK FOOTER //
// ./src/store/modules/account-creation/types.js