export default {
  summaryLoading: false,
  hasLoadedSummary: false,
  categories: [],
  catergoriesLoading: false,
  hasLoadedCategories: false,
  partnersByID: {},
  partnersLoading: false,
  hasLoadedPartners: false,
  offersSummaryByCategory: {},
  offersSummaryByCategoryLoading: false,
  hasLoadedOffersSummaryByCategory: false,
  offersLimitedTime: [],
  offersLimitedTimeLoading: false,
  hasLoadedLimitedtime: false,
  offersTrending: [],
  offersTrendingLoading: false,
  hasLoadedTrending: false,
  collections: [],
  collectionsLoading: false,
  hasLoadedCollections: false,
  searchTags: [],
  searchTagsLoading: false,
  hasLoadedSearchTags: false,
  offerLegal: null,
  offerLegalLoading: false,
  hasLoadedOfferLegal: false,
  contests: [],
  contestsLoading: false,
  hasLoadedContests: false,
  ads: [],
  adsLoading: false,
  hasLoadedAds: false,
  favouriteOffers: [],
  favouriteOffersLoading: false,
  hadLoadedFavouriteOffers: false,
  isMostredeemed: true,
  offers: {},
  offersLoading: false,
  hasLoadedOffers: false,
  savedList: [],
  savedListLoading: false,
  hadSavedList: false,
  offersByCategory: {},
  hasLoadedOffersByCategory: false,
  partnersByCategory: {},
  hasLoadedPartnersByCategory: false
}



// WEBPACK FOOTER //
// ./src/store/modules/offers/state.js