export const LOAD_CATEGORIES = 'LOAD_CATEGORIES'
export const LOAD_OFFERS = 'LOAD_OFFERS'
export const LOAD_LIMITED_TIME = 'LOAD_LIMITED_TIME'
export const LOAD_TRENDING = 'LOAD_TRENDING'
export const LOAD_COLLECTIONS = 'LOAD_COLLECTIONS'
export const LOAD_SEARCH_TAGS = 'LOAD_SEARCH_TAGS'
export const LOAD_OFFER_LEGAL = 'LOAD_OFFER_LEGAL'
export const LOAD_CONTESTS = 'LOAD_CONTESTS'
export const LOAD_ADS = 'LOAD_ADS'
export const LOAD_FAVOURITE_OFFERS = 'LOAD_FAVOURITE_OFFERS'
export const UPDATE_PARTNER_MAP = 'UPDATE_PARTNER_MAP'
export const UPDATE_FLAG = 'UPDATE_FLAG'
export const LOAD_OFFER_SUMMARY = 'LOAD_OFFER_SUMMARY'
export const LOAD_SAVED_LIST = 'LOAD_SAVED_LIST'
export const LOAD_OFFERS_BY_CATEGORY = 'LOAD_OFFERS_BY_CATEGORY'
export const LOAD_PARTNERS_BY_CATEGORY = 'LOAD_PARTNERS_BY_CATEGORY'



// WEBPACK FOOTER //
// ./src/store/modules/offers/types.js